service: pmb-plus-ssr-poc

plugins:
  - serverless-nextjs-plugin


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: 
    NODE_ENV: dev





package:
  exclude:
    - ./**

custom:
  secrets: ${file(secrets.json)}
  serverless-nextjs:
    nextConfigDir: ./
  #apigwBinary:
    #types:
     # - '*/*'
  #serverless-offline:
    #port: 4000
  #customDomain:
   #domainName: ${self:custom.secrets.DOMAIN}
    #basePath: ''
    #stage: ${self:custom.secrets.NODE_ENV}
    #createRoute53Record: true
    #certificateName: '.'