service: pmb-plus-ssr-poc



provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}


plugins:
  - serverless-nextjs-plugin

package:
  exclude:
    - ./**

custom:
  secrets: ${file(secrets.json)}
  serverless-nextjs:
    nextConfigDir: ./
  #apigwBinary:
    #types:
     # - '*/*'
  #serverless-offline:
    #port: 4000
  #customDomain:
   #domainName: ${self:custom.secrets.DOMAIN}
    #basePath: ''
    #stage: ${self:custom.secrets.NODE_ENV}
    #createRoute53Record: true
    #certificateName: '.'